import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/GG.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Egor Glebov personal website</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
