name: Deploy React + Vite

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Vite project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 8080
          script: |
            SITE_DIR=/var/www/geeg.tatar

            mkdir -p $SITE_DIR

            rsync -avz --delete ./dist/ $SITE_DIR/

            sudo systemctl reload nginx
